{
  imports = [
    ./containers/bazarr-anime.nix
    ./containers/bazarr.nix
    ./containers/fileflows.nix
    ./containers/huntarr.nix
    ./containers/jellyfin.nix
    ./containers/lidarr.nix
    ./containers/overseerr.nix
    ./containers/plex.nix
    ./containers/prowlarr.nix
    ./containers/radarr-anime.nix
    ./containers/radarr.nix
    ./containers/sabnzbd.nix
    ./containers/sonarr-anime.nix
    ./containers/sonarr.nix
    ./containers/tailscale.nix
    ./containers/traefik.nix
    ./containers/uptime-kuma.nix
  ];
}
